name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  format:
    name: Rustfmt

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enforce formatting
      run: cargo fmt --check

  linter:
    name: Clippy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Linting
      run: cargo clippy -- -D warnings

  coverage:
    name: Coverage

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    - name: Generate report
      run: cargo llvm-cov report --html --output-dir coverage
    - uses: actions/upload-artifact@v4
      with:
        name: "Coverage report"
        path: coverage/

  
    
